version: '3.9'

services:
  db:
    image: airflow
    command: db init
    volumes:
      - ./config:/root/airflow
  
  webserver:
    image: airflow
    command: webserver
    ports:
      - 80:8080
    volumes:
      - ./config:/root/airflow
    depends_on:
      - db
      - scheduler
  
  scheduler:
    image: airflow
    command: scheduler
    volumes:
      - ./config:/root/airflow
    depends_on:
      - db
